Repository CivMC/CivDocker, pull requests merged in 2023-01, with the labels that each got.

#94 Fix a small mistake in the Gold Forge pickaxe table
  paper/config/plugins/FactoryMod/config.yml
Labels: Category: Bug, Priority: Medium

#90 Disable compensatory Bee spawning
  paper/config/plugins/SimpleAdminHacks/config.yml
Labels: Category: Feature, Priority: Low

#100 Fix WB
  paper/config/plugins/Citadel/config.yml
Labels: Category: Bug, Priority: High
