Repository CivMC/CivDocker, pull requests merged in 2023-07, with the labels that each got.

#173 Replace BetterChairs with Gsit
  paper/config/plugins/BetterChairs/config.yml
  paper/config/plugins/CombatTagPlus/config.yml
  paper/config/plugins/GSit/config.yml
  paper/config/plugins/GSit/emotes/Aqua-trail.gex
  paper/config/plugins/GSit/emotes/Fire-trail.gex
  paper/config/plugins/GSit/emotes/Gold-trail.gex
  paper/config/plugins/GSit/emotes/Love-trail.gex
  paper/config/plugins/GSit/emotes/Music-trail.gex
  paper/config/plugins/GSit/emotes/Orange-trail.gex
  paper/config/plugins/GSit/emotes/Pink-trail.gex
  paper/config/plugins/GSit/emotes/Red-trail.gex
  paper/config/plugins/GSit/emotes/Smoke-trail.gex
  paper/config/plugins/GSit/emotes/Soul-Fire-trail.gex
  paper/config/plugins/GSit/emotes/black-trail.gex
  paper/config/plugins/GSit/emotes/blue-trail.gex
  paper/config/plugins/GSit/emotes/green-trail.gex
  paper/plugins/BetterChairs-1.2.0.jar
  paper/plugins/GSit-1.4.9.jar
Labels: Category: Bug, Category: Feature, Priority: Medium

#171 Lower Stone&Iron acid maturation times
  paper/config/plugins/Citadel/config.yml
Labels: Priority: High, Category: Enchancement

#169 Update worlds.yml
  paper/config/plugins/RandomSpawn/worlds.yml
Labels: Priority: Low, Category: Enchancement

#165 Make kill messages Global
  paper/config/plugins/CivChat2/config.yml
Labels: Priority: Low, Meta: Discussion Needed, Category: Enchancement

#164 Disable some outdated/less usefull dogfacts. Added a couple new ones …
  paper/config/plugins/SimpleAdminHacks/config.yml
Labels: Priority: Low, Category: Enchancement
